language: c

os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
matrix:
  exclude:
   - os: osx
     arch: ppc64le
compiler: gcc
sudo: false
addons:
  apt:
    packages:
      libpcap-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update         ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libpcap; fi
  
before_script: autoreconf -if
script: ./configure && make
